# Generated by Django 4.2.6 on 2026-01-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chepareta', '0003_add_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
